Models/Dish.cs
#pragma warning disable CS8618

//Allows you use a feature of C# to do validations
using System.ComponentModel.DataAnnotations;

namespace CRUDelicious.Models;

public class Dish
{
    [Key]
    public int DishId { get; set; }

    [Required]
    [MinLength(2, ErrorMessage = "Name must be longer than 2 characters")]
    [MaxLength(45, ErrorMessage = "Name cannot be longer than 45 characters")]
    public string Name { get; set; }

    [Required]
    [MinLength(2, ErrorMessage = "Chef's name must be longer than 2 characters")]
    [MaxLength(45, ErrorMessage = "Chef's name cannot be longer than 45 characters")]
    public string Chef { get; set; }

    [Required]
    [MinLength(5, ErrorMessage = "Description must be longer than 5 characters")]
    public string Description { get; set; }

    [Required]
    [Range(1, Int32.MaxValue, ErrorMessage = "Calories must be greater than 0")]
    public int Calories { get; set; }

    [Required]
    [Range(1, 5, ErrorMessage = "Tastiness must be between 1 and 5")]
    public int Tastiness { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;
}

Models/ErrorViewModel.cs
namespace CRUDelicious.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/MyContext.cs
//goes in Models folder
#pragma warning disable CS8618
// We can disable our warnings safely because we know the framework will assign non-null values 
// when it constructs this class for us.
using Microsoft.EntityFrameworkCore;
namespace CRUDelicious.Models;
// the MyContext class represents a session with our MySQL database, allowing us to query for or save data
// DbContext is a class that comes from EntityFramework, we want to inherit its features
public class MyContext : DbContext 
{   
    // This line will always be here. It is what constructs our context upon initialization  
    public MyContext(DbContextOptions options) : base(options) { }    
    // We need to create a new DbSet<Model> for every model in our project that is making a table
    // The name of our table in our database will be based on the name we provide here
    // This is where we provide a plural version of our model to fit table naming standards    
    public DbSet<Dish> Dishes { get; set; } 
}

Controllers/DishController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CRUDelicious.Models;

namespace EFLecture.Controllers;

public class DishController : Controller
{
    private readonly ILogger<DishController> _logger;

    private MyContext db;

    public DishController(ILogger<DishController> logger, MyContext context)
    {
        _logger = logger;
        db = context;
    }

    [HttpGet("")]
    public IActionResult Index()
    {
        List<Dish> allDishes = db.Dishes.ToList();
        return View("Dashboard", allDishes);
    }

    [HttpGet("dishes/new")]
    public IActionResult NewDish()
    {
        return View("New");
    }

    [HttpPost("dishes/create")]
    public IActionResult CreateDish(Dish newDish)
    {
        if (!ModelState.IsValid)
        {
            return View("New");
        }
        db.Dishes.Add(newDish);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet("dishes/{dishId}")]
    public IActionResult ViewDish(int dishId)
    {
        Dish? dish = db.Dishes.FirstOrDefault(dish => dish.DishId == dishId);
        if (dish == null)
        {
            return RedirectToAction("Index");
        }
        return View("ViewDish", dish);
    }

    [HttpGet("dishes/{dishId}/edit")]
    public IActionResult Edit(int dishId)
    {
        Dish? dish = db.Dishes.FirstOrDefault(dish => dish.DishId == dishId);
        if (dish == null)
        {
            return RedirectToAction("Index");
        }
        return View("Edit", dish);
    }

    [HttpPost("dishes/{dishId}/update")]
    public IActionResult Update(Dish editDish, int dishId)
    {
        if (!ModelState.IsValid)
        {
            return Edit(dishId);
        }
        Dish? dish = db.Dishes.FirstOrDefault(dish => dish.DishId == dishId);
        if (dish == null)
        {
            return RedirectToAction("Index");
        }
        dish.Name = editDish.Name;
        dish.Chef = editDish.Chef;
        dish.Description = editDish.Description;
        dish.Calories = editDish.Calories;
        dish.Tastiness = editDish.Tastiness;
        db.Dishes.Update(dish);
        db.SaveChanges();
        return RedirectToAction("ViewDish", new {dishId = dishId});
    }

    [HttpPost("dishes/{dishId}")]
    public IActionResult Delete(int dishId)
    {
        Dish? dish = db.Dishes.FirstOrDefault(dish => dish.DishId == dishId);
        db.Dishes.Remove(dish);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CRUDelicious.Models;

namespace CRUDelicious.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Dish/Dashboard.cshtml
@{
    ViewData["Title"] = "CRUDelicious";
}

@model List<Dish>

<div class="text-center">
    <h1 class="display-4">Welcome to @ViewData["Title"]</h1>
</div>

<div class="d-flex justify-content-center gap-3 my-3">
    <a asp-controller="Dish" asp-action="Index" class="link text-dark">Home</a>
    <span>|</span>
    <a asp-controller="Dish" asp-action="NewDish" class="link text-dark">Add a Dish</a>
</div>

<div>
    <p class="ms-3">Check out some recent dishes</p>
    <hr class="w-50 my-3">
@foreach(Dish dish in Model)
{
    <p class="my-3 ms-3"><a asp-controller="Dish" asp-action="ViewDish" asp-route-dishId="@dish.DishId" class="link">@dish.Name</a> by @dish.Chef</p>
}
</div>

Views/Dish/Edit.cshtml
@{
    ViewData["Title"] = "Add a New Dish!";
}

@model Dish

<div class="text-center">
    <h1 class="display-4">Edit @Model.Name</h1>
</div>
<div class="container w-75 mx-auto">
    <form asp-controller="Dish" asp-action="Update" asp-route-dishId="@Model.DishId" method="post" class="shadow p-3 rounded">
        <div class="d-flex justify-content-evenly">
            <div>
                <div class="mb-3">
                    <label asp-for="Chef" class="my-2"></label>
                    <input asp-for="Chef" type="text" class="form-control">
                    <span asp-validation-for="Chef" class="text-danger fw-bold"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Name" class="my-2"></label>
                    <input asp-for="Name" type="text" class="form-control">
                    <span asp-validation-for="Name" class="text-danger fw-bold"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Calories" class="my-2"></label>
                    <input asp-for="Calories" type="number" class="form-control">
                    <span asp-validation-for="Calories" class="text-danger fw-bold"></span>
                </div>
            </div>
            <div>
                <label asp-for="Tastiness" class="my-2"></label>
                <input asp-for="Tastiness" type="number" class="form-control">
                <span asp-validation-for="Tastiness" class="text-danger fw-bold"></span>
            </div>
            <div>
                <label asp-for="Description" class="my-2"></label>
                <textarea asp-for="Description" cols="30" rows="7" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger fw-bold"></span>
                <div class="d-flex justify-content-end my-3">
                    <button class="btn btn-outline-info">Submit</button>
                </div>
            </div>
        </div>
    </form>
</div>

Views/Dish/New.cshtml
@{
    ViewData["Title"] = "Add a New Dish!";
}

@model Dish

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
</div>
<div class="container w-75 mx-auto">
    <form asp-action="CreateDish" asp-controller="Dish" method="post" class="shadow p-3 rounded">
        <div class="d-flex justify-content-evenly">
            <div>
                <div class="mb-3">
                    <label asp-for="Chef" class="my-2"></label>
                    <input asp-for="Chef" type="text" class="form-control">
                    <span asp-validation-for="Chef" class="text-danger fw-bold"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Name" class="my-2"></label>
                    <input asp-for="Name" type="text" class="form-control">
                    <span asp-validation-for="Name" class="text-danger fw-bold"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Calories" class="my-2"></label>
                    <input asp-for="Calories" type="number" class="form-control">
                    <span asp-validation-for="Calories" class="text-danger fw-bold"></span>
                </div>
            </div>
            <div>
                <label asp-for="Tastiness" class="my-2"></label>
                <input asp-for="Tastiness" type="number" class="form-control">
                <span asp-validation-for="Tastiness" class="text-danger fw-bold"></span>
            </div>
            <div>
                <label asp-for="Description" class="my-2"></label>
                <textarea asp-for="Description" cols="30" rows="7" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger fw-bold"></span>
                <div class="d-flex justify-content-end my-3">
                    <button class="btn btn-outline-info">Submit</button>
                    </div>
            </div>
        </div>
    </form>
</div>

Views/Dish/ViewDish.cshtml
@{
    ViewData["Title"] = "View Dish Page";
}

@model Dish

<div class="text-center">
    <h1 class="display-4">@Model.Name</h1>
</div>

<div class="d-flex justify-content-center gap-3 my-3">
    <a asp-controller="Dish" asp-action="Index" class="link text-dark">Home</a>
    <span>|</span>
    <a asp-controller="Dish" asp-action="NewDish" class="link text-dark">Add a Dish</a>
</div>

<div class="d-flex flex-column">
    <p class="ms-3">@Model.Name by @Model.Chef</p>
    <hr class="w-50 my-3">
    <div class="ms-3 d-flex flex-column gap-3">
        <h6>Description: @Model.Description</h6>
        <h6>Calories: @Model.Calories</h6>
        <h6>Tastiness: @Model.Tastiness</h6>
    </div>
</div>
<div class="d-flex justify-content-evenly w-50 my-3">
    <form asp-controller="Dish" asp-action="Delete" asp-route-dishId="@Model.DishId">
        <button class="btn btn-outline-danger">Delete</button>
    </form>
    <a asp-controller="Dish" asp-action="Edit" asp-route-dishId="@Model.DishId" class="btn btn-outline-warning">Edit</a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDelicious</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUDelicious.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dish" asp-action="Index">CRUDelicious</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="NewDish">Add Dish</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CRUDelicious - <a asp-area="" asp-controller="Dish" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>